# Generated by Django 5.2.1 on 2025-05-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField()),
                ('descricao', models.CharField()),
                ('ni', models.CharField()),
                ('responsavel', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=60)),
                ('mac_address', models.CharField(max_length=60)),
                ('unidade_med', models.CharField(max_length=17)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ambientes')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.sensores')),
            ],
        ),
    ]
