# Generated by Django 5.2.1 on 2025-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_ambientes_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura (°C)'), ('Luminosidade', 'Luminiosidade (lux)'), ('Umidade', 'Umidade (%)'), ('Contador', 'Contador (num)')]),
        ),
    ]
