# Generated by Django 5.2.1 on 2025-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_ambientes_descricao_alter_ambientes_ni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='sig',
            field=models.IntegerField(),
        ),
    ]
