# Generated by Django 5.2.1 on 2025-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_sensores_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='ambiente',
            new_name='ambiente_id',
        ),
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura (°C)', 'Temperatura (°C)'), ('Luminosidade (lux)', 'Luminiosidade (lux)'), ('Umidade (%)', 'Umidade (%)'), ('Contador (num)', 'Contador (num)')], max_length=18),
        ),
    ]
