# Generated by Django 5.2.1 on 2025-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_ambiente_historico_ambiente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='ambiente_id',
            new_name='ambiente',
        ),
    ]
